#include "compiler.h"
#include "lexer.h"
#include "parser.h"
#include <iostream>
#include <fstream>
#include <sstream>

Compiler::Compiler() 
    : lexer(std::make_unique<Lexer>()),
      parser(std::make_unique<Parser>()) {}

Compiler::~Compiler() {}

bool Compiler::compile(const std::string& inputFile, const std::string& outputFile) {
    try {
        std::cout << "Step 1: Reading source file..." << std::endl;
        std::string sourceCode;
        if (!readSourceFile(inputFile, sourceCode)) {
            std::cerr << "ERROR: Failed to read input file: " << inputFile << std::endl;
            return false;
        }
        std::cout << "OK: Read " << sourceCode.length() << " bytes\n";

        std::cout << "\nStep 2: Lexical analysis (tokenization)..." << std::endl;
        if (!lexer) {
            std::cerr << "ERROR: Lexer not initialized\n";
            return false;
        }
        
        auto tokens = lexer->tokenize(sourceCode);
        std::cout << "OK: Generated " << tokens.size() << " tokens\n";

        std::cout << "\nStep 3: Syntax analysis (parsing)..." << std::endl;
        if (!parser) {
            std::cerr << "ERROR: Parser not initialized\n";
            return false;
        }
        
        auto ast = parser->parse(tokens);
        if (!ast) {
            std::cerr << "ERROR: AST generation failed\n";
            return false;
        }
        std::cout << "OK: AST generated successfully\n";

        std::cout << "\nStep 4: Code generation..." << std::endl;
        std::string generatedCode = "#include <iostream>\n";
        generatedCode += "#include <cstdint>\n\n";
        generatedCode += "/* Generated by W3D Compiler */\n\n";
        generatedCode += sourceCode;
        generatedCode += "\n\n/* Compilation complete */\n";
        std::cout << "OK: Code generated (" << generatedCode.length() << " bytes)\n";

        std::cout << "\nStep 5: Writing output file..." << std::endl;
        if (!writeOutputFile(outputFile, generatedCode)) {
            std::cerr << "ERROR: Failed to write output file: " << outputFile << std::endl;
            return false;
        }
        std::cout << "OK: Output written to " << outputFile << "\n";

        std::cout << "\n========================================\n";
        std::cout << "SUCCESS: Compilation completed!\n";
        std::cout << "========================================\n";
        return true;

    } catch (const std::exception& e) {
        std::cerr << "EXCEPTION: " << e.what() << std::endl;
        return false;
    } catch (...) {
        std::cerr << "UNKNOWN ERROR: Unexpected exception occurred\n";
        return false;
    }
}

bool Compiler::readSourceFile(const std::string& filename, std::string& content) {
    try {
        std::ifstream file(filename, std::ios::in | std::ios::binary);
        
        if (!file.is_open()) {
            std::cerr << "  Cannot open file: " << filename << std::endl;
            return false;
        }

        file.seekg(0, std::ios::end);
        std::streamsize size = file.tellg();
        file.seekg(0, std::ios::beg);

        if (size > 10485760) {  // 10MB limit
            std::cerr << "  File too large: " << size << " bytes (max 10MB)\n";
            return false;
        }

        content.resize(size);
        if (!file.read(content.data(), size)) {
            std::cerr << "  Error reading file data\n";
            return false;
        }

        file.close();
        std::cout << "  File size: " << size << " bytes\n";
        return true;

    } catch (const std::exception& e) {
        std::cerr << "  Exception: " << e.what() << std::endl;
        return false;
    }
}

bool Compiler::writeOutputFile(const std::string& filename, const std::string& content) {
    try {
        std::ofstream file(filename, std::ios::out | std::ios::binary);
        
        if (!file.is_open()) {
            std::cerr << "  Cannot create file: " << filename << std::endl;
            return false;
        }

        if (!file.write(content.c_str(), content.length())) {
            std::cerr << "  Error writing file data\n";
            return false;
        }

        file.close();
        std::cout << "  File size: " << content.length() << " bytes\n";
        return true;

    } catch (const std::exception& e) {
        std::cerr << "  Exception: " << e.what() << std::endl;
        return false;
    }
}
